name: End-to-end tests
on: [push]
jobs:
  cypress-tests:
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      matrix:
        # run 3 copies of the current job in parallel
        containers: [1, 2, 3]
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      # Install Currents
      - name: Install currents
        run: yarn add @currents/cli

      # Run all Cypress tests
      - name: Run Cypress on Currents.dev
        uses: cypress-io/github-action@v2
        with:
          command: yarn currents run --record --parallel --key ${{ secrets.CURRENTS_RECORD_KEY }}
