name: End-to-end tests

on:
  pull_request:
    types:
      - opened
      - edited
      - synchronize

jobs:
  cypress-tests:
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      matrix:
        # run 3 copies of the current job in parallel
        containers: [1, 2, 3]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      # Install Currents
      - name: Install dependencies
        run: yarn install --ci

      # Run all Cypress tests
      - name: Run Cypress on Currents.dev
        uses: cypress-io/github-action@v2
        with:
          command: yarn currents run --record --parallel --browser chrome --key ${{ secrets.CURRENTS_RECORD_KEY }} --ci-build-id "${{ github.repository }}-${{ github.run_id }}-${{ github.run_attempt}}"
